name: Dev Task
description: 개발 작업 정의
title: "[DEV] "
labels: ["dev"]

body:
  - type: textarea
    id: context
    attributes:
      label: Context
      description: 이 작업이 필요한 이유
      placeholder: ex) 로그인 API에서 토큰 만료 처리 필요
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: 이번 작업에서 포함되는 범위
      placeholder: |
        - 로그인 API 수정
        - 토큰 만료 처리
        - 에러 메시지 개선
    validations:
      required: true

  - type: textarea
    id: etc
    attributes:
      label: etc
      description: 기타사항
      placeholder: 기타사항
